const blog = [
    {
        id: 1,
        thumb: "https://mowgarden.com/wp-content/uploads/2023/03/cay-phong-thuy-hop-menh-kim.jpg",
        title: "Top 10 cây phong thủy hợp mệnh Kim giúp kích hoạt vượng khí và mang lại may mắn.",
        desc: "Cây lan chi là loại cây trong nhà được trồng phổ biến, nhờ khả năng phủ xanh hiệu quả mà lại rất dễ chăm sóc, đôi khi bỏ mặc không tưới vẫn có thể sống tốt. Chính vì có sức sống mãnh liệt mà Cây Lan Chi được xem là biểu tượng cho sự kiên cường, bền bỉ và vượt khó. Loại cây này rất hợp với người mệnh Kim. Trong phong thủy, Cây Lan Chi được xem là có khả năng giúp xua đuổi tà ma, điềm xui xẻo, đem lại sự sung túc và may mắn cho gia chủ. Khả năng thanh lọc không khí cực đỉnh của loại cây này cũng được xem là món bảo bối mà bạn nên cân nhắc sở hữu.1 cay co lan chi hop menh kim Cây Lan Chi có thể hấp thụ đến 95% khí Cacbonic, đồng thời nó cũng hấp thụ các loại chất khí độc hại trong không khí, biến những chất khí gây hại này thành đường và amino acid. Người mệnh Kim có thể đặt Cây Lan Chi trên bàn làm để chúng tiếp sức mạnh cho bạn mỗi ngày.Hoặc bạn có thể lựa chọn loại cây này để khử mùi cho nhà bếp, phòng ăn, nhà tắm hoặc nhà vệ sinh. Đôi khi bạn cũng có thể trồng trong chậu treo và đặt chúng ở cửa sổ, hiên nhà… giúp tăng tính thẩm mỹ cho không gian sống.",
        titleName: "Cây lan chi",
        thumbDetail: "https://mowgarden.com/wp-content/uploads/2023/04/1-cay-co-lan-chi-hop-menh-kim-1067x800.jpg",
    },
    {
        id: 2,
        thumb: "https://mowgarden.com/wp-content/uploads/2023/04/huong-dan-trong-cay-phong-thuy-trong-nha-1068x800.jpg",
        title: "Hướng dẫn lựa chọn cây phong thủy trong nhà để tăng vượng khí",
        desc: "Đầu tiên, việc sử dụng cây cảnh trong ngôi nhà mang lại vẻ đẹp tự nhiên cho không gian sống. Đa phân trong số đó là những loại cây để bàn, cây lớn trồng chậu, cây thủy sinh hoặc những loại cây dây leo, đôi lúc là những loại cây bonsai có dáng độc đáo được lựa chọn để trang trí cho ngôi nhà. Việc bổ sung thêm những loại cây cảnh trong nhà này sẽ giúp cho không gian sống trở nên tươi mới và đón nhận năng lượng tích cực",
        titleName: "Ý nghĩa của cây xanh trong phong thủy",
        thumbDetail: "https://mowgarden.com/wp-content/uploads/2023/04/huong-dan-trong-cay-phong-thuy-trong-nha-1068x800.jpg",
    },
    {
        id: 3,
        thumb: "https://mowgarden.com/wp-content/uploads/2023/03/cay-hanh-phuc-la-cay-gi.jpg",
        title: "Cây hạnh phúc là cây gì? Hướng dẫn cách chăm sóc cây hạnh phúc trong nhà",
        desc: "Cây hạnh phúc có tên khoa học là Radermachera sinica, thuộc họ Bignoniaceae, là một giống cây thân gỗ có nguồn gốc từ khu vực Đông Nam Á, bao gồm Việt Nam, Lào, Campuchia, Thái Lan, Malaysia và Indonesia. Tuy nhiên, hiện nay cây hạnh phúc cũng được trồng rộng rãi ở nhiều nơi trên thế giới, bao gồm cả châu Âu và Bắc Mỹ. Cây hạnh phúc có thân cây vươn cao, hưởng thẳng, có nhiều nhánh tỏa ra xung quanh và có bộ lá xanh rất xum xuê màu xanh đậm. Với đặc điểm rậm rạm, màu xanh đậm và tươi mới quanh năm, cây hạnh phúc rất thích hợp để phủ xanh không gian sống. Người ta thường trồng cây hạnh phúc vào trong chậu để trưng trong nhà hoặc trồng dưới đất để tạo bóng mát. Loài cây này có sức sống rất bền bỉ, có thể tạo hình thành các dáng cây khác nhau từ một thân, 2 tầng, 3 tầng hoặc thậm chí 5 tầng, và đôi khi nó còn được tạo dáng bonsai rất độc đáo.",
        titleName: "Giới thiệu về cây hạnh phúc",
        thumbDetail: "https://mowgarden.com/wp-content/uploads/2023/03/cay-hanh-phuc.jpg",
    },
    {
        id: 4,
        thumb: "https://mowgarden.com/wp-content/uploads/2021/04/cach-cham-soc-cay-ngu-gia-bi-1.jpg",
        title: "Hướng Dẫn Cách Trồng Cây Ngũ Gia Bì",
        desc: "Đối với những cây non, đặc biệt là một số loại cây trồng thủy sinh thì hầu như không cần chất dinh dưỡng. Chúng sống dựa vào không khí các bạn ạ. Đùa thôi. Thực ra các loại cây non của chúng ta có nhu cầu về dinh dưỡng rất ít, nên hầu như không cần phân bón vẫn có thể phát triển được. Một tháng bạn có thể hòa tan khoảng 1 muỗng phân hữu cơ để bón. Khi cây lớn, có nhiều nhánh phát triển um xùm thì ta bắt đầu nghĩ đến việc bón phân cho chúng được rồi. Với một lượng lá và thân nhiều thì bạn cần đảm bảo nguồn dinh dưỡng đầy đủ cho chúng phát triển ổn định. Không có dinh dưỡng thì cây vẫn có thể sống tốt. Đây là phương pháp để các nghệ nhân tạo dáng bonsai cây. Gọi là bỏ đói cây để cây tự dưỡng, thường có tốc độ phát triển chậm chạm, và tập trung và thân là chủ yếu. Nên để có được một cây ngũ gia bì bonsai sẽ phải tốn rất nhiều thời gian. Ngừng cho ăn khi nhiệt độ giảm hoặc bất cứ khi nào cây không hoạt động. Bạn cũng có thể muốn giảm hoặc dừng hoàn toàn một cách nghiêm túc khi bạn quyết định rằng nó đủ cao và đã đạt đến chiều cao cuối cùng (hoặc mong muốn).",
        titleName: "Nên bón phân thế nào và vào lúc nào?",
        thumbDetail: "	https://mowgarden.com/wp-content/uploads/2021/04/cach-cham-soc-cay-ngu-gia-bi-3.jpg",
    },
    {
        id: 5,
        thumb: "https://mowgarden.com/wp-content/uploads/2021/04/cong-dung-cay-ngu-gia-bi-1-1.jpg",
        title: "Đặc điểm, ý nghĩa và tác dụng của cây ngũ gia bì",
        desc: "Tương truyền, cây ngũ gia bì là một loài cây có khả năng đuổi muỗi rất tốt, nhưng có thật là loài cây này đuổi được muỗi hay không? Trên thực tế, khi trồng cây ngũ gia bì trong vườn, thì tôi nhận thấy muỗi có vẻ không dám lại gần cây này. Có thể muỗi sợ một loại chất nào đó có trong cây, nhưng tác dụng thì không thần kì như nhiều trang báo viết. Theo các tài liệu khoa học, bên trong vỏ thân của cây ngũ gia bì chân chim có chứa Asiaticoside. Chất Asiaticoside và scheffoleoside B được phân lập từ vỏ thân cây Schefflera heptaphylla. Tên danh pháp của Asiaticoside là 1-O-acyl-D-glucose pyranose, là một hợp chất hưu cơ được tìm thấy trong tự nhiên. Chính loại chất Asiaticoside này đã giúp đuổi muổi hiệu quả, nhưng với nồng độ khá ít nên trên thực tế thì bạn chỉ trồng có vài cây này nên hiệu quả đuổi muỗi chẳng là bao cả. Ngoài ra, Asiaticoside là một chất có khả năng kháng khuẩn tự nhien và có hoạt tính diệt nấm chống lại được mầm bệnh và nấm. Đây là cơ chế kháng bệnh tự nhiên tuyệt vời của cây ngũ gia bì chân chim.",
        titleName: "Cây ngũ gia bì chống muỗi",
        thumbDetail: "https://mowgarden.com/wp-content/uploads/2021/04/cay-ngu-gia-bi-3-1.jpg",
    },
    {
        id: 6,
        thumb: "https://mowgarden.com/wp-content/uploads/2021/04/cach-cham-soc-cay-trong-nha-800x501.jpg",
        title: "Hướng Dẫn Cách Chăm Sóc Cây Cảnh Trong Nhà",
        desc: "Vốn dĩ trong tự nhiên cây cối đã tồn tại cơ chế sinh tồn trong mã gen của chúng rồi nên chúng ta không nên tác động quá nhiều mà hãy để chúng tự sống theo đúng tự nhiên đã lập trình. Do đó, thay vì chăm chút quá nhiều thì hãy quan sát cây xanh nhiều hơn, rồi từ đó hiểu về cách chúng đã sinh tồn ra sao. Khi đã hiểu về cây xanh rồi thì ta sẽ dễ dàng biết cách cung cấp đúng những thứ mà chúng thật sự cần. Trồng cây cảnh là một “thú chơi” mang lại những trải nghiệm rất khác nhau cho mỗi người. Mục đích của việc trồng cây trong nhà cũng sẽ khác nhau hẳn, vì có người thì trồng cây cảnh như là một món đồ để trang trí nhà cửa, để chụp hình khoe lên mạng xã hội hoặc đơn giản là vì ý nghĩa phong thủy của loại cây đó. Sau tất cả, thì chúng ta cây xanh cũng chẳng khác gì một món đồ. Với tâm trạng của một người chơi như vậy thì ai mà lại không muốn cây lúc nào cũng luôn xanh tốt và phải lớn thật nhanh. Chúng ta tìm tới những “bí thuật” để điều khiển cây cối theo mong muốn của mình. Và rồi mọi thứ không theo như ý muốn thì cái cây đó xem như hết giá trị “lợi dụng”, và nó như một món đồ cần phải “thanh lý môn hộ” cho rộng chỗ. Nếu quan sát thì bạn cũng nhận ra rằng là trong tự nhiên chẳng có một loại thuốc kích rễ nào, cũng chẳng có phân bón N-P-K hay thuốc trừ sâu gì cả nhưng tại sao cây cối vẫn luôn phát triển xanh tốt đấy thôi. Bản năng sinh tồn tuyệt vời của cây cối chỉ được kích hoạt khi chúng phải đối mặt với điều kiện khó khăn. Tương tự vậy, khi đặt chúng ta vào nhưng hoàn cảnh khốn khó thì tự bản thân phải động não suy nghĩ làm sao để tồn tại được. Nếu như tưới ít nước thì cây sẽ phải kích hoạt cơ chế sinh tồn của chúng, bộ rễ bắt đầu cảm nhận tình trạng thiếu nước và nó buộc phải sản xuất các hóc-môn sinh trưởng giúp kích thích phân sinh, làm cho bộ rễ dài ra để tìm tới được nguồn nước. Trong bản năng sinh tồn bằng mọi giá phải tìm được nguồn nước vì nếu không chúng sẽ bị chết khô. Bạn thấy đấy, mong muốn của chúng ta không thể quyết được sự sinh trưởng của cây mà chỉ nên quan sát chúng rồi sau đó cung cấp cho cây côi những thứ chúng cần. Chỉ cần giúp cây có được môi trường sống thuận lợi thì cây sẽ phát triển xanh tốt, không cần phải dùng “bí thuật” gì ở đây cả. Hơn nữa điều này cũng giúp bạn “nhẹ gánh” hơn phần nào trong việc chăm sóc cây xanh.",
        titleName: "Kiên nhẫn quan sát cây xanh",
        thumbDetail: "https://mowgarden.com/wp-content/uploads/2021/04/cua-hang-ban-cay-trong-nha.jpg",
    },
];
export default blog;
